listener 8883
cafile C:/Users/Daniel Williams/Documents/hydroficient-project/certs/ca.pem
certfile C:/Users/Daniel Williams/Documents/hydroficient-project/certs/server.pem
keyfile C:/Users/Daniel Williams/Documents/hydroficient-project/certs/server-key.pem
require_certificate false
allow_anonymous true
